[package]
name = "dehtml_capi"
version = "0.1.0"
authors = ["Stacey Ell <stacey.ell@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
serde_json = "*"
libc = "*"

[dependencies.dehtml]
path = ".."
